config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "flats#index"
  get 'dashboard', to: 'pages#dashboard'
  # patch 'flats/:id/like', to: 'flats#like', as: :like_flat

  resources :flats do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]

    collection do
      get :map
    end

    member do
      patch :like
    end
  end

  resources :bookings, only: [:destroy]
  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  attr_accessor :check_in, :total

  belongs_to :flat
  belongs_to :user
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :booking
  belongs_to :tenant, class_name: "User"
  has_many :messages
  
  validates :booking, uniqueness: { scope: :tenant,
    message: "you already have a chat with this booking" }
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many_attached :photos

  acts_as_votable

  TYPES = %w(flat maisonette detached)

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address_and_property_type,
    against: [ :name, :address, :property_type ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  validates :content, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :flats
  has_many :bookings

  has_many :chatrooms_as_user1, class_name: "Chatroom", foreign_key: :user_1
  has_many :chatrooms_as_user2, class_name: "Chatroom", foreign_key: :user_2

  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.nickname
    self.email.match(/^([^@]+)/)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.flat = @flat
    if @booking.save!
      flash[:notice] = "You book #{@booking.flat.name}"
      name = "#{current_user.email.match(/^([^@]+)/)} / #{@flat.user.email.match(/^([^@]+)/)}"
      Chatroom.create!(booking: @booking, tenant: current_user, name: name)
      redirect_to dashboard_path
    else
      render 'flats/show', status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, status: 303
    # respond_to do |format|
    #   format.html {redirect_to dashboard_path}
    # end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  # def create
  #   user1 = current_user
  #   user2 = User.find(params[:user_id])
  #   name = "#{user1.email.match(/^([^@]+)/)} / #{user2.email.match(/^([^@]+)/)}"
  #   chatroom = Chatroom.new(user_1: user1, user_2: user2, name: name)
  #   if chatroom.save!
  #     redirect_to chatroom_path(chatroom)
  #   else
  #     render 'pages/dashboard', stauts: :unprocessable_entity
  #   end
  # end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController


  # skip_before_action :authenticate_user!, only: :index
  before_action :set_flat, only: [:show, :like]

  def map
    @flats = Flat.all

    if params[:query].present?
      @flats = Flat.search_by_name_and_address_and_property_type(params[:query])
    end

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end


  def index
    @flats = Flat.all
    if params[:query].present?
      @flats = Flat.search_by_name_and_address_and_property_type(params[:query])
    end
  end


  def like
    if current_user.voted_up_on? @flat
      @flat.unvote_by current_user
    else
      @flat.upvote_by current_user
    end

    respond_to do |format|
      format.html do
        redirect_to flats_path
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@flat, partial: 'flats/flat', locals: {flat: @flat})
      end
    end
  end


  def show
    @booking = Booking.new
    @review = Review.new
    @markers = [{
        lat: @flat.latitude,
        lng: @flat.longitude
      }]
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save!
      redirect_to flats_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :guests, :price, :property_type, photos: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
   def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      redirect_to chatroom_path(@chatroom)
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @flat = Flat.find(params[:flat_id])
    @review = Review.new(review_params)
    @review.flat = @flat
    @review.user = current_user

    respond_to do |format|
      if @review.save!
        format.html { redirect_to flat_path(@flat)}
        format.json
      else
        format.html { render "monuments/new", status: :unprocessable_entity }
        format.json
      end

    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [flat, booking], data: {controller: "flatpickr", flatpickr_price_value: "#{flat.price}"} do |f| %>
  <%= f.input :check_in, label: 'Check In/Out', input_html: { data: {flatpickr_target: "checkIn"}}%>
  <%= f.input :start_date, :as => :hidden, input_html: { data: {flatpickr_target: "start"}} %>
  <%= f.input :end_date, :as => :hidden,  input_html: { data: {flatpickr_target: "end"}} %>
  <div ><p>£ <span class="bg-warning text-white p-2 ms-2" data-flatpickr-target= "total">0.00</span></p> </div>
  <%= f.submit 'Book', class: 'btn btn-warning w-100' %>
<% end %>

app/views/chatrooms/show.html.erb
<div class="container chatroom">
  <h1>#<%= @chatroom.name %></h1>

  <div class="messages">
    <% @chatroom.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <small>
          <strong><%= message.user.nickname %></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.content %></p>
      </div>
    <% end %>
  </div>
  <%= simple_form_for [@chatroom, @message],
    html: {class: "d-flex"} do |f|
  %>
    <%= f.input :content,
      label: false,
      placeholder: "Message ##{@chatroom.name}",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>
</div>

app/views/flats/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide w-75 me-4" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% flat.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %> " data-bs-interval="3000">
        <%= cl_image_tag photo.key , class: "d-block w-100", height: 400 %>
      </div>
    <% end %>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/flats/_flat.html.erb
 <div id="<%= dom_id flat %>" class="flat-card">
  <%= link_to flat.name, flat_path(flat) %>
  <%= render 'like_link', flat: flat %>
  <span><%= flat.votes_for.size %></span>
</div>

app/views/flats/_like_link.html.erb
<%= link_to like_flat_path(flat), data: {turbo_method: :patch} do %>
  <% if current_user.voted_for? flat %>
    <i class="far fa-thumbs-up" style="color: red;"></i>
  <% else %>
    <i class="far fa-thumbs-up"></i>
  <% end %>
<% end %>

app/views/flats/index.html.erb
<div class="container">

  <h1>Welcome to Right Move 99 </h1>
  <div class="row justify-content-center">
    <div class="col-8 my-3 d-flex">
      <%# <%= link_to 'Map', map_flats_path, class: 'btn btn-info mx-3' %>
      <%= form_with url: map_flats_path, method: :get, class: "d-flex" do %>
        <%= hidden_field_tag 'flats', @flats %>
        <%= submit_tag 'map', class: 'btn btn-info' %>
      <% end %>

    </div>


  </div>
  <hr>
  
  <ul>
    <% @flats.each do |flat| %>
      <li><%= render 'flat', flat: flat %></li>
    <% end %>
  </ul>
</div>

app/views/flats/map.html.erb
<div class='container'>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <button onclick="history.back()">Go Back</button>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new House</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :guests %>
    <%= f.input :property_type, collection: Flat::TYPES %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit class: 'btn btn-info' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container">

  <div class="w-100">
    <h1><%= @flat.name %></h1>
    <div class="d-flex">
      <%= render 'carousel', flat: @flat %>

      <div style="width: 25%; height: 400px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

  <div class="d-flex mt-4">
    <% @flat.photos.each do |photo| %>
      <div class="ms-2">
        <%= cl_image_tag photo.key , height: 100, width: 150, crop: :fill %>
      </div>
    <% end %>
  </div>

  <%# Modal Test %>

  <div class="d-flex justify-content-between align-items-start mt-5">
      <div>
        <p> 📍 <%= @flat.address %></p>
        <p> 👥 <%= @flat.guests %></p>
        <p> £ <%= @flat.price %> per day</p>
        <p> Owner: <%= @flat.user.email.match(/^([^@]+)/) %></p>
      </div>

    <div class="booking-form w-25">
      <%= render 'bookings/form', {flat: @flat, booking: @booking}  %>
    </div>

  </div>

  <%# Reviews %>
  <div class="reviews-container d-flex mt-4 p-4" data-controller="insert-reviews">
    <div class="review-form w-50 me-3">
      <h2>Leave a Review</h2>
      <%= render 'reviews/form', { flat: @flat, review: @review } %>
    </div>
    <div class="review-form w-50 ms-2" data-insert-reviews-target="list">
      <% @flat.reviews.each do |review| %>
        <%= render 'reviews/review', review: review %>
      <% end %>
    </div>
  </div>

</div>

app/views/flats/vote.js.erb
document.getElementById("upvote-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rightmove - UK's number one property website for properties for sale and to rent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/_message_link.html.erb
<%# <% if Chatroom.where(user_1: 2, user_2: current_user.id).empty? %>
  <%#= form_with url: chatrooms_path, method: :post, class: "d-flex" do %>
    <%#= hidden_field_tag :user_id,
          current_user.id
      %>
    <%#= submit_tag "Send a message", name: "", class: "btn btn-primary" %>
  <%# end %>
<%# else %>
<%# end %>

<%= link_to "Send a message", chatroom_path(Chatroom.where(booking: booking)[0]), class: "btn btn-primary"%>

app/views/pages/dashboard.html.erb
<div class="container"  >
  <h1>Dashboard</h1>
  <ul class="list-group">
    <% current_user.bookings.each do |booking| %>
      <li class="list-group-item list-group-item-success" data-controller="bookings" data-bookings-id-value="<%= booking.id%>">
        <p><%= booking.flat.name %></p>
        from: <%= booking.start_date.strftime("%A %d %b %Y") %> to: <%= booking.end_date.strftime("%A %d %b %Y") %>
        <%= render 'message_link', booking: booking %> |
        <%= link_to booking_path(booking), data: {turbo_method: :delete, turbo_confirm: 'Are you sure'} do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for [flat, review],
  data: {
    insert_reviews_target: "form",
    action: "insert-reviews#insert"
  } do |f|%>
  <%= f.input :rating, collection: (1..5) %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review-card">
  <p>from: <%= review.user.email %></p>
  <p><%= '⭐️' * review.rating %></p>
  <p><%= review.content %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_search.html.erb
<%= form_with url: flats_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Type a keyword"
    %>
  <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
<% end %>